// flow-typed signature: ac88096da508bb81376630952c5f806b
// flow-typed version: <<STUB>>/react-datepicker_vv2.10.1/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datepicker/dist/es' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist/react-datepicker' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist/react-datepicker.min' {
  declare module.exports: any;
}

declare module 'react-datepicker/es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datepicker/dist/es/index' {
  declare module.exports: $Exports<'react-datepicker/dist/es'>;
}
declare module 'react-datepicker/dist/es/index.js' {
  declare module.exports: $Exports<'react-datepicker/dist/es'>;
}
declare module 'react-datepicker/dist/index' {
  declare module.exports: $Exports<'react-datepicker/dist'>;
}
declare module 'react-datepicker/dist/index.js' {
  declare module.exports: $Exports<'react-datepicker/dist'>;
}
declare module 'react-datepicker/dist/react-datepicker.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker'>;
}
declare module 'react-datepicker/dist/react-datepicker.min.js' {
  declare module.exports: $Exports<
    'react-datepicker/dist/react-datepicker.min'
  >;
}
declare module 'react-datepicker/es/index' {
  declare module.exports: $Exports<'react-datepicker/es'>;
}
declare module 'react-datepicker/es/index.js' {
  declare module.exports: $Exports<'react-datepicker/es'>;
}
